services:
  mp4forge:
    image: ghcr.io/jessielw/mp4forge:latest
    platform: linux/amd64
    container_name: mp4forge-web
    ports:
      - "8000:8000"
    volumes:
      # mount for persistent config and logs
      - /SOME_PATH/runtime:/app/runtime
    environment:
      - PYTHONUNBUFFERED=1
    restart: "no"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s
